Zadanie 1. (1pkt) Napisz procedurę szachowica(n,k), która rysuje kwadratową szachownicę, o boku
2*n, składającą się z kwadratów o boku k, jak na poniższym rysunku (na którym pokazany jest wynik
wywołania szachownica(4,3) ).

In [142]:
def szachownica(n, y):
   for i in range (n):
         for i in range (y):
            print((" "*n +"#"*n)*n)
         for i in range (y):
            print(("#"*n + " "*n)*n)
  
szachownica(5,3)


     #####     #####     #####     #####     #####
     #####     #####     #####     #####     #####
     #####     #####     #####     #####     #####
#####     #####     #####     #####     #####     
#####     #####     #####     #####     #####     
#####     #####     #####     #####     #####     
     #####     #####     #####     #####     #####
     #####     #####     #####     #####     #####
     #####     #####     #####     #####     #####
#####     #####     #####     #####     #####     
#####     #####     #####     #####     #####     
#####     #####     #####     #####     #####     
     #####     #####     #####     #####     #####
     #####     #####     #####     #####     #####
     #####     #####     #####     #####     #####
#####     #####     #####     #####     #####     
#####     #####     #####     #####     #####     
#####     #####     #####     #####     #####     
     #####     #####     #####     #####     #####
     #####     #####     ##### 

In [100]:
import numpy 

A= numpy.arange(9).reshape(3, 3)
print(A)
print(" ")
B=numpy.transpose(A)
print(B)
M=A*B






[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [177]:
cyfry = {}

cyfry[0] = """
 ###  
#   #
#   #
#   #
 ###
"""

cyfry[1] = """
  #
 ##
  #
  #
 ###
"""

cyfry[4] = """
 # 
#
#####
  #
  #
"""


cyfry[2] = """
 ###  
#   #
  ##
 #
#####
"""

cyfry[5] = """
##### 
#   
####
    #
####
"""

cyfry[8] = """
 ###  
#   #
 ### 
#   #
 ###
"""

cyfry[6] = """
 ###  
#   
#### 
#   #
 ###
"""

cyfry[9] = """
 ###  
#   #
 ####
    #
 ###
"""

cyfry[3] = """
####  
    #
 ### 
    #
####
"""

cyfry[7] = """
#####
   #
 ###
 #
# 
"""

pytajnik = """
 ###  
#   #
  ##
   
  #
"""

def popraw(s):
    L = s.split('\n')
    for i in range(len(L)):
        if len(L[i]) < 5:
            L[i] += (5-len(L[i])) * " "
        else:
            L[i] = L[i][:5]   
    return L[1:-1]      

def daj_cyfre(n):
   if n not in range(10):
       return popraw(pytajnik)
   return popraw(cyfry[n])

def dlc(n):
    
dlc(12345)

//DLC=12345
for i in range str(DLC):
    for i in range (5):
        print(daj_cyfre(4)[i], end="")


  #    ###  ####   #    ##### 
 ##   #   #     # #     #     
  #     ##   ###  ##### ####  
  #    #        #   #       # 
 ###  ##### ####    #   ####  


In [137]:
kolo="""
  ###
 #####
#######
#######
 #####
  ###
"""

x=kolo.split('\n')
print("\n".join(x))



  ###
 #####
#######
#######
 #####
  ###



SyntaxError: invalid syntax (<ipython-input-136-05115bcf280f>, line 11)

In [160]:
def koperta(n):
    for i in range (n):
        for j in range(n):
            if i==j or i==0 or i==n-1 or j==0 or j==n-1 or i==(n-j)-1:
                print('*', end='')
            else:
                print(" ",end="")
                
        print()

koperta(7)
        

*******
**   **
* * * *
*  *  *
* * * *
**   **
*******


In [ ]:
def dlc(n):
    lista = list(str(n))
    for i in range(5):
        for j in lista:
            cyfra = daj_cyfre(int(j))
            print(cyfra[i], end=' ')
        print()

dlc(12345)